account/urls.py
from django.urls import path

from account.views import (
	account_view,
	edit_account_view,
	crop_image,
)

app_name = 'account'

urlpatterns = [

	path('<user_id>/', account_view, name="view"),
	path('<user_id>/edit/', edit_account_view, name="edit"),
	path('<user_id>/edit/cropImage/', crop_image, name="crop_image"),

	
]

chat/urls.py
from django.urls import path

from chat.views import(
	private_chat_room_view,
	create_or_return_private_chat,
)

app_name = 'chat'

urlpatterns = [
	path('', private_chat_room_view, name='private-chat-room'),
	path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

freedom/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from main.views import (
	home_screen_view
)

from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,

)

urlpatterns = [
	path('', home_screen_view, name='home'),
    path('account/', include('account.urls', namespace='account')),
	path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('search/', account_search_view, name="search"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




chat/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone

from notification.models import Notification

class PrivateChatRoom(models.Model):
	"""
	A private room for people to chat in.
	"""
	user1               = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user1")
	user2               = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user2")

	# Users who are currently connected to the socket (Used to keep track of unread messages)
	connected_users     = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="connected_users")

	is_active 			= models.BooleanField(default=False)

	def connect_user(self, user):
		"""
		return true if user is added to the connected_users list
		"""
		is_user_added = False
		if not user in self.connected_users.all():
			self.connected_users.add(user)
			is_user_added = True
		return is_user_added 


	def disconnect_user(self, user):
		"""
		return true if user is removed from connected_users list
		"""
		is_user_removed = False
		if user in self.connected_users.all():
			self.connected_users.remove(user)
			is_user_removed = True
		return is_user_removed

	@property
	def group_name(self):
		"""
		Returns the Channels Group name that sockets should subscribe to to get sent
		messages as they are generated.
		"""
		return f"PrivateChatRoom-{self.id}"


class RoomChatMessageManager(models.Manager):
	def by_room(self, room):
		qs = RoomChatMessage.objects.filter(room=room).order_by("-timestamp")
		return qs

class RoomChatMessage(models.Model):
	"""
	Chat message created by a user inside a Room
	"""
	user                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	room                = models.ForeignKey(PrivateChatRoom, on_delete=models.CASCADE)
	timestamp           = models.DateTimeField(auto_now_add=True)
	content             = models.TextField(unique=False, blank=False,)

	objects = RoomChatMessageManager()

	def __str__(self):
		return self.content



class UnreadChatRoomMessages(models.Model):
	"""
	Keep track of the number of unread messages by a specific user in a specific private chat.
	When the user connects the chat room, the messages will be considered "read" and 'count' will be set to 0.
	"""
	room                = models.ForeignKey(PrivateChatRoom, on_delete=models.CASCADE, related_name="room")

	user                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

	count               = models.IntegerField(default=0)

	most_recent_message = models.CharField(max_length=500, blank=True, null=True)

	# last time msgs were read by the user
	reset_timestamp     = models.DateTimeField()

	notifications       = GenericRelation(Notification)


	def __str__(self):
		return f"Messages that {str(self.user.username)} has not read yet."

	def save(self, *args, **kwargs):
		if not self.id: # if just created, add a timestamp. Otherwise do not automatically change it ever.
			self.reset_timestamp = timezone.now()
		return super(UnreadChatRoomMessages, self).save(*args, **kwargs)

	@property
	def get_cname(self):
		"""
		For determining what kind of object is associated with a Notification
		"""
		return "UnreadChatRoomMessages"

	@property
	def get_other_user(self):
		"""
		Get the other user in the chat room
		"""
		if self.user == self.room.user1:
			return self.room.user2
		else:
			return self.room.user1


@receiver(post_save, sender=PrivateChatRoom)
def create_unread_chatroom_messages_obj(sender, instance, created, **kwargs):
	if created:
		unread_msgs1 = UnreadChatRoomMessages(room=instance, user=instance.user1)
		unread_msgs1.save()

		unread_msgs2 = UnreadChatRoomMessages(room=instance, user=instance.user2)
		unread_msgs2.save()



@receiver(pre_save, sender=UnreadChatRoomMessages)
def increment_unread_msg_count(sender, instance, **kwargs):
	"""
	When the unread message count increases, update the notification. 
	If one does not exist, create one. (This should never happen)
	"""
	if instance.id is None: # new object will be created
		pass # create_unread_chatroom_messages_obj will handle this scenario
	else:
		previous = UnreadChatRoomMessages.objects.get(id=instance.id)
		if previous.count < instance.count: # if count is incremented
			content_type = ContentType.objects.get_for_model(instance)
			if instance.user == instance.room.user1:
				other_user = instance.room.user2
			else:
				other_user = instance.room.user1
			try:
				notification = Notification.objects.get(target=instance.user, content_type=content_type, object_id=instance.id)
				notification.verb = instance.most_recent_message
				notification.timestamp = timezone.now()
				notification.save()
			except Notification.DoesNotExist:
				instance.notifications.create(
					target=instance.user,
					from_user=other_user,
					redirect_url=f"{settings.BASE_URL}/chat/?room_id={instance.room.id}", # we want to go to the chatroom
					verb=instance.most_recent_message,
					content_type=content_type,
				)


@receiver(pre_save, sender=UnreadChatRoomMessages)
def remove_unread_msg_count_notification(sender, instance, **kwargs):
	"""
	If the unread messge count decreases, it means the user joined the chat. So delete the notification.
	"""
	if instance.id is None: # new object will be created
		pass # create_unread_chatroom_messages_obj will handle this scenario
	else:
		previous = UnreadChatRoomMessages.objects.get(id=instance.id)
		if previous.count > instance.count: # if count is decremented
			content_type = ContentType.objects.get_for_model(instance)
			try:
				notification = Notification.objects.get(target=instance.user, content_type=content_type, object_id=instance.id)
				notification.delete()
			except Notification.DoesNotExist:
				pass
				# Do nothing

public_chat/models.py
from django.db import models
from django.conf import settings


class PublicChatRoom(models.Model):

	# Room title
	title 				= models.CharField(max_length=255, unique=True, blank=False,)

	# all users who are authenticated and viewing the chat
	users 				= models.ManyToManyField(settings.AUTH_USER_MODEL, help_text="users who are connected to chat room.", blank=True, null=True)

	def __str__(self):
		return self.title


	def connect_user(self, user):
		"""
		return true if user is added to the users list
		"""
		is_user_added = False
		if not user in self.users.all():
			self.users.add(user)
			self.save()
			is_user_added = True
		elif user in self.users.all():
			is_user_added = True
		return is_user_added 


	def disconnect_user(self, user):
		"""
		return true if user is removed from the users list
		"""
		is_user_removed = False
		if user in self.users.all():
			self.users.remove(user)
			self.save()
			is_user_removed = True
		return is_user_removed 


	@property
	def group_name(self):
		"""
		Returns the Channels Group name that sockets should subscribe to to get sent
		messages as they are generated.
		"""
		return "PublicChatRoom-%s" % self.id


class PublicRoomChatMessageManager(models.Manager):
    def by_room(self, room):
        qs = PublicRoomChatMessage.objects.filter(room=room).order_by("-timestamp")
        return qs

class PublicRoomChatMessage(models.Model):
    """
    Chat message created by a user inside a PublicChatRoom
    """
    user                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room                = models.ForeignKey(PublicChatRoom, on_delete=models.CASCADE)
    timestamp           = models.DateTimeField(auto_now_add=True)
    content             = models.TextField(unique=False, blank=False,)

    objects = PublicRoomChatMessageManager()

    def __str__(self):
        return self.content

public_chat/views.py
from django.shortcuts import render

# Create your views here.

public_chat/templates/public_chat/snippets/public_chat_room.html
{% load static %}
<style type="text/css">
	.chat-log {
		height: 500px;
		overflow-x: hidden;
		overflow-y: auto;
		padding: 10px;
		background-color: #fff;
		font-size: 0.9em;
		flex-direction: column-reverse;
	}
	.profile-image{
		width: 33px;
		height: 33px;
		margin-top: 0px;
		margin-bottom: auto;
	}
	.profile-image:hover{
		cursor: pointer;
	}
	.username-span{
		font-weight: 600;
		margin-top: 0px;
		margin-bottom: auto;
		margin-left: 5px;
		margin-right: 5px;
	}
	.username-span:hover{
		cursor: pointer;
	}
	.msg-p{
		font-weight: 450;
		margin-top: 5px;
		margin-bottom: auto;
		margin-left: 5px;
		margin-right: 5px;
		white-space: normal;
		-ms-word-break: break-all;
		word-break: break-all;
	}
	.message-container{
		margin-top: 10px;
		justify-content: start;
	}
	.timestamp-span{
		font-weight: 400;
		font-size: 0.8em;
		color: var(--secondary-text-color);
	}
	.timestamp-span:hover{
		cursor: pointer;
	}
	#id_chatroom_loading_spinner{
			position: absolute;
	}
	.connected-users{
		color: red;
	}
	.connected-users-icon{
		color: red;
	}
	.connected-users-icon:hover{
		cursor: default;
	}
</style>

{% if debug %}
PUBLIC CHAT
{% endif %}
<span class="{% if not debug %}d-none{% endif %} page-number" id="id_page_number">1</span>

<div class="card mt-3">
	<div class="card-header">
		<div class="d-flex flex-row justify-content-between">
			<h3 class="">Public Chat</h3>
			<div class="d-flex flex-row align-items-center">
				<span class="material-icons m-auto pr-1 connected-users-icon">person_outline</span>
				<span class="m-auto connected-users" id="id_connected_users"></span>
			</div>
			
		</div>
	</div>
	<div class="card-body p-1">
		<div class="d-flex flex-column" id="id_chat_log_container">
			<div class="d-flex flex-row justify-content-center" id="id_chatroom_loading_spinner_container">
				<div class="spinner-border text-primary"  id="id_chatroom_loading_spinner" role="status"  style="display: none; ">
					<span class="sr-only">Loading...</span>
				</div>
			</div>
			<div class="d-flex chat-log" id="id_chat_log">
				
			</div>
			<div class="d-flex chat-message-input-container">
				<textarea class="flex-grow-1 chat-message-input" id="id_chat_message_input"></textarea>
				<button class="btn btn-primary chat-message-submit-button">
					<span id="id_chat_message_submit" class="material-icons">send
					</span>
				</button>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	
	// Correctly decide between ws:// and wss://
	var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
	{% if debug_mode %}
		var ws_path = ws_scheme + '://' + window.location.host + "/public_chat/{{room_id}}/"; // development
	{% else %}
		var ws_path = ws_scheme + '://' + window.location.host + ":8001/public_chat/{{room_id}}/"; // production
	{% endif %}
	var public_chat_socket = new WebSocket(ws_path);

	// Handle incoming messages
	public_chat_socket.onmessage = function(message) {
		// console.log("Got chat websocket message " + message.data);
		var data = JSON.parse(message.data);

		// display the progress bar?
		displayChatroomLoadingSpinner(data.display_progress_bar)

		// Handle errors (ClientError)
		if (data.error) {
			console.error(data.error + ": " + data.message)
			showClientErrorModal(data.message)
			return;
		}
		// Handle joining (Client perspective)
		if (data.join) {
			console.log("Joining public room " + data.join);
			getRoomChatMessages()
		}

		// Handle getting a message
		if (data.msg_type == 0) {
			appendChatMessage(data, true, true)
		}
		// Handle getting the connected_user count
		if (data.msg_type == 1) {
			setConnectedUsersCount(data['connected_user_count'])
		}
		// new payload of messages coming in from backend
		if(data.messages_payload){
			handleMessagesPayload(data.messages, data.new_page_number)
		}
	};

	public_chat_socket.addEventListener("open", function(e){
	console.log("Public Public ChatSocket OPEN")
		// join chat room
		if("{{request.user.is_authenticated}}"){
			public_chat_socket.send(JSON.stringify({
				"command": "join",
				"room": "{{room_id}}"
			}));
		}
	})

	public_chat_socket.onclose = function(e) {
		console.error('Public ChatSocket closed.');
	};

	public_chat_socket.onOpen = function(e){
		console.log("Public ChatSocket onOpen", e)
	}

	public_chat_socket.onerror = function(e){
        console.log('Public ChatSocket error', e)
    }

    if (public_chat_socket.readyState == WebSocket.OPEN) {
    	console.log("Public ChatSocket OPEN")
    } else if (public_chat_socket.readyState == WebSocket.CONNECTING){
        console.log("Public ChatSocket connecting..")
    }

	document.getElementById('id_chat_message_input').focus();
	document.getElementById('id_chat_message_input').onkeyup = function(e) {
		if (e.keyCode === 13 && e.shiftKey) {  // enter + return
			// Handled automatically by textarea
		}
		else if(e.keyCode === 13 && !e.shiftKey){ // enter + !return
			document.getElementById('id_chat_message_submit').click();
		}
	};

    document.getElementById('id_chat_message_submit').onclick = function(e) {
		const messageInputDom = document.getElementById('id_chat_message_input');
		const message = messageInputDom.value;
		public_chat_socket.send(JSON.stringify({
			"command": "send",
			"message": message,
			"room_id": "{{room_id}}"
		}));
		messageInputDom.value = '';
	};

	function appendChatMessage(data, maintainPosition, isNewMessage){
		message = data['message']
		msg_id = data['msg_id']
		uName = data['username']
		user_id = data['user_id']
		profile_image = data['profile_image']
		timestamp = data['natural_timestamp']
		
		var msg = message + '\n';
		var username = uName + ": "
		createChatMessageElement(msg, msg_id, username, profile_image, user_id, timestamp, maintainPosition, isNewMessage)
	}

	function handleMessagesPayload(messages, new_page_number){
		if(messages != null && messages != "undefined" && messages != "None"){
			setPageNumber(new_page_number)
			messages.forEach(function(message){
				appendChatMessage(message, true, false)
			})
		}
		else{
			setPaginationExhausted() // no more messages
		}
	}

	function setPageNumber(pageNumber){
		document.getElementById("id_page_number").innerHTML = pageNumber
	}

	function setPaginationExhausted(){
		setPageNumber("-1")
	}

	/*
		Retrieve the chat room messages given the page number.
	*/
	function getRoomChatMessages(){
		var pageNumber = document.getElementById("id_page_number").innerHTML
		if(pageNumber != "-1"){
			setPageNumber("-1") // Do not allow any other queries while one is in progress
			public_chat_socket.send(JSON.stringify({
				"command": "get_room_chat_messages",
				"room_id": "{{room_id}}",
				"page_number": pageNumber,
			}));
		}
	}

	/*
		Get the next page of chat messages when scrolls to bottom
	*/
	document.getElementById("id_chat_log").addEventListener("scroll", function(e){
		var chatLog = document.getElementById("id_chat_log")
		chatLog.addEventListener("scroll", function(e){
			if ((Math.abs(chatLog.scrollTop) + 2) >= (chatLog.scrollHeight - chatLog.offsetHeight)) {
				getRoomChatMessages()
			}
		});
	})

	function createChatMessageElement(msg, msg_id, username, profile_image, user_id, timestamp, maintainPosition, isNewMessage){
		var chatLog = document.getElementById("id_chat_log")

		var newMessageDiv = document.createElement("div")
		newMessageDiv.classList.add("d-flex")
		newMessageDiv.classList.add("flex-row")
		newMessageDiv.classList.add("message-container")

		var profileImage = document.createElement("img")
		profileImage.addEventListener("click", function(e){
			selectUser(user_id)
		})
		profileImage.classList.add("profile-image")
		profileImage.classList.add("rounded-circle")
		profileImage.classList.add("img-fluid")
		profileImage.src = "{% static 'img/dummy_image.png' %}"
		var profile_image_id = "id_profile_image_" + msg_id
		profileImage.id = profile_image_id
		newMessageDiv.appendChild(profileImage)

		var div1 = document.createElement("div")
		div1.classList.add("d-flex")
		div1.classList.add("flex-column")

		var div2 = document.createElement("div")
		div2.classList.add("d-flex")
		div2.classList.add("flex-row")

		var usernameSpan = document.createElement("span")
		usernameSpan.addEventListener("click", function(e){
			selectUser(user_id)
		})
		usernameSpan.classList.add("username-span")
		usernameSpan.innerHTML = username
		div2.appendChild(usernameSpan)

		var timestampSpan = document.createElement("span")
		timestampSpan.innerHTML = timestamp
		timestampSpan.classList.add("timestamp-span")
		timestampSpan.classList.add("d-flex")
		timestampSpan.classList.add("align-items-center")
		timestampSpan.addEventListener("click", function(e){
			selectUser(user_id)
		})
		div2.appendChild(timestampSpan)

		div1.appendChild(div2)

		var msgP = document.createElement("p")
		msgP.innerHTML = validateText(msg)
		msgP.classList.add("msg-p")
		div1.appendChild(msgP)

		newMessageDiv.appendChild(div1)

		if(isNewMessage){
			chatLog.insertBefore(newMessageDiv, chatLog.firstChild)
		}
		else{
			chatLog.appendChild(newMessageDiv)
		}
		
		if(!maintainPosition){
			chatLog.scrollTop = chatLog.scrollHeight
		}

		// now that a default image is showing, load the actual image.
		preloadImage(profile_image, profile_image_id) // called from base_js.html
	}

	function selectUser(user_id){
		// Weird work-around for passing arg to url
		var url = "{% url 'account:view' user_id=53252623623632623 %}".replace("53252623623632623", user_id)
		var win = window.open(url, "_blank")
		win.focus()
	}

	function showClientErrorModal(message){
		document.getElementById("id_client_error_modal_body").innerHTML = message
		document.getElementById("id_trigger_client_error_modal").click()
	}

	function displayChatroomLoadingSpinner(isDisplayed){
		var spinner = document.getElementById("id_chatroom_loading_spinner")
		if(isDisplayed){
			spinner.style.display = "block"
		}
		else{
			spinner.style.display = "none"
		}
	}

	function setConnectedUsersCount(count){
		element = document.getElementById("id_connected_users")
		element.innerHTML = count
	}
</script>


<!-- Client Error MODAL -->
<button type="button" id="id_trigger_client_error_modal" class="d-none btn btn-primary" data-toggle="modal" data-target="#id_client_error_modal">
</button>
<div class="modal fade" id="id_client_error_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Socket Client Error</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="id_client_error_modal_body">Something went wrong.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="id_client_error_modal_close_btn">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- Client Error MODAL -->