chat/urls.py
from django.urls import path

from chat.views import(
	private_chat_room_view,
	create_or_return_private_chat,
)

app_name = 'chat'

urlpatterns = [
	path('', private_chat_room_view, name='private-chat-room'),
	path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

freedom/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from main.views import (
	home_screen_view
)

from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,

)

urlpatterns = [
	path('', home_screen_view, name='home'),
    path('account/', include('account.urls', namespace='account')),
	path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('search/', account_search_view, name="search"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from account.models import Account


class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

	class Meta:
		model = Account
		fields = ('email', 'username', 'password1', 'password2', )

	def clean_email(self):
		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('username', 'email', 'profile_image', 'hide_email' )

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" is already in use.' % account)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError('Username "%s" is already in use.' % username)


    def save(self, commit=True):
        account = super(AccountUpdateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email'].lower()
        account.profile_image = self.cleaned_data['profile_image']
        account.hide_email = self.cleaned_data['hide_email']
        if commit:
            account.save()
        return account

templates/password_reset/password_change.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>


<form id="id_password_change_form" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
    <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password" required="true">
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required="true">
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>  
</form>


{% endblock %}

templates/password_reset/password_change_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been Updated.</p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a> now.</p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

	<div class="d-flex flex-column">
		  <p class="m-auto p-2">
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'home' %}">Return to home page</a></p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Open-Chat Team
{% endautoescape %}

templates/password_reset/password_reset_form.html
{% extends 'base.html' %}


{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>


<form id="id_password_reset_form" method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
    <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true" >
  <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" >Send reset email</button>  
</form>



{% endblock %}