chat/urls.py
from django.urls import path

from chat.views import(
	private_chat_room_view,
	create_or_return_private_chat,
)

app_name = 'chat'

urlpatterns = [
	path('', private_chat_room_view, name='private-chat-room'),
	path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

freedom/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from main.views import (
	home_screen_view
)

from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,

)

urlpatterns = [
	path('', home_screen_view, name='home'),
    path('account/', include('account.urls', namespace='account')),
	path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('register/', register_view, name="register"),
    path('search/', account_search_view, name="search"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




friend/urls.py
from django.urls import path

from friend.views import(
	send_friend_request,
	friend_requests,
	accept_friend_request,
	remove_friend,
	decline_friend_request,
	cancel_friend_request,
	friends_list_view,
)

app_name = 'friend'

urlpatterns = [
	path('list/<user_id>', friends_list_view, name='list'),
	path('friend_remove/', remove_friend, name='remove-friend'),
    path('friend_request/', send_friend_request, name='friend-request'),
    path('friend_request_cancel/', cancel_friend_request, name='friend-request-cancel'),
    path('friend_requests/<user_id>/', friend_requests, name='friend-requests'),
    path('friend_request_accept/<friend_request_id>/', accept_friend_request, name='friend-request-accept'),
    path('friend_request_decline/<friend_request_id>/', decline_friend_request, name='friend-request-decline'),
]

friend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import json

from account.models import Account
from friend.models import FriendRequest, FriendList


def friends_list_view(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		if user_id:
			try:
				this_user = Account.objects.get(pk=user_id)
				context['this_user'] = this_user
			except Account.DoesNotExist:
				return HttpResponse("That user does not exist.")
			try:
				friend_list = FriendList.objects.get(user=this_user)
			except FriendList.DoesNotExist:
				return HttpResponse(f"Could not find a friends list for {this_user.username}")
			
			# Must be friends to view a friends list
			if user != this_user:
				if not user in friend_list.friends.all():
					return HttpResponse("You must be friends to view their friends list.")
			friends = [] # [(friend1, True), (friend2, False), ...]
			# get the authenticated users friend list
			auth_user_friend_list = FriendList.objects.get(user=user)
			for friend in friend_list.friends.all():
				friends.append((friend, auth_user_friend_list.is_mutual_friend(friend)))
			context['friends'] = friends
	else:		
		return HttpResponse("You must be friends to view their friends list.")
	return render(request, "friend/friend_list.html", context)


def friend_requests(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		account = Account.objects.get(pk=user_id)
		if account == user:
			friend_requests = FriendRequest.objects.filter(receiver=account, is_active=True)
			context['friend_requests'] = friend_requests
		else:
			return HttpResponse("You can't view another users friend requets.")
	else:
		redirect("login")
	return render(request, "friend/friend_requests.html", context)


def send_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			receiver = Account.objects.get(pk=user_id)
			try:
				# Get any friend requests (active and not-active)
				friend_requests = FriendRequest.objects.filter(sender=user, receiver=receiver)
				# find if any of them are active (pending)
				try:
					for request in friend_requests:
						if request.is_active:
							raise Exception("You already sent them a friend request.")
					# If none are active create a new friend request
					friend_request = FriendRequest(sender=user, receiver=receiver)
					friend_request.save()
					payload['response'] = "Friend request sent."
				except Exception as e:
					payload['response'] = str(e)
			except FriendRequest.DoesNotExist:
				# There are no friend requests so create one.
				friend_request = FriendRequest(sender=user, receiver=receiver)
				friend_request.save()
				payload['response'] = "Friend request sent."

			if payload['response'] == None:
				payload['response'] = "Something went wrong."
		else:
			payload['response'] = "Unable to sent a friend request."
	else:
		payload['response'] = "You must be authenticated to send a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")


def accept_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "GET" and user.is_authenticated:
		friend_request_id = kwargs.get("friend_request_id")
		if friend_request_id:
			friend_request = FriendRequest.objects.get(pk=friend_request_id)
			# confirm that is the correct request
			if friend_request.receiver == user:
				if friend_request: 
					# found the request. Now accept it
					updated_notification = friend_request.accept()
					payload['response'] = "Friend request accepted."

				else:
					payload['response'] = "Something went wrong."
			else:
				payload['response'] = "That is not your request to accept."
		else:
			payload['response'] = "Unable to accept that friend request."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to accept a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")


def remove_friend(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			try:
				removee = Account.objects.get(pk=user_id)
				friend_list = FriendList.objects.get(user=user)
				friend_list.unfriend(removee)
				payload['response'] = "Successfully removed that friend."
			except Exception as e:
				payload['response'] = f"Something went wrong: {str(e)}"
		else:
			payload['response'] = "There was an error. Unable to remove that friend."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to remove a friend."
	return HttpResponse(json.dumps(payload), content_type="application/json")



def decline_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "GET" and user.is_authenticated:
		friend_request_id = kwargs.get("friend_request_id")
		if friend_request_id:
			friend_request = FriendRequest.objects.get(pk=friend_request_id)
			# confirm that is the correct request
			if friend_request.receiver == user:
				if friend_request: 
					# found the request. Now decline it
					updated_notification = friend_request.decline()
					payload['response'] = "Friend request declined."
				else:
					payload['response'] = "Something went wrong."
			else:
				payload['response'] = "That is not your friend request to decline."
		else:
			payload['response'] = "Unable to decline that friend request."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to decline a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")




def cancel_friend_request(request, *args, **kwargs):
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			receiver = Account.objects.get(pk=user_id)
			try:
				friend_requests = FriendRequest.objects.filter(sender=user, receiver=receiver, is_active=True)
			except FriendRequest.DoesNotExist:
				payload['response'] = "Nothing to cancel. Friend request does not exist."

			# There should only ever be ONE active friend request at any given time. Cancel them all just in case.
			if len(friend_requests) > 1:
				for request in friend_requests:
					request.cance()
				payload['response'] = "Friend request canceled."
			else:
				# found the request. Now cancel it
				friend_requests.first().cancel()
				payload['response'] = "Friend request canceled."
		else:
			payload['response'] = "Unable to cancel that friend request."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to cancel a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")



friend/templates/friend/snippets/accept_friend_request.html
<script type="text/javascript">
	
	function acceptFriendRequest(friend_request_id, uiUpdateFunction){
		var url = "{% url 'friend:friend-request-accept' friend_request_id=53252623623632623 %}".replace("53252623623632623", friend_request_id)
		$.ajax({
			type: 'GET',
			dataType: "json",
			url: url,
			timeout: 5000,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request accepted."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
	

</script>

friend/templates/friend/snippets/cancel_friend_request.html
<script type="text/javascript">
	
	function cancelFriendRequest(id, uiUpdateFunction){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'friend:friend-request-cancel' %}",
			data: payload,
			timeout: 5000,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request canceled."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
	

</script>

friend/templates/friend/snippets/decline_friend_request.html
<script type="text/javascript">
	
	function declineFriendRequest(friend_request_id, uiUpdateFunction){
		var url = "{% url 'friend:friend-request-decline' friend_request_id=53252623623632623 %}".replace("53252623623632623", friend_request_id)
		$.ajax({
			type: 'GET',
			dataType: "json",
			url: url,
			timeout: 5000,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request declined."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
	

</script>

friend/templates/friend/snippets/remove_friend.html
<script type="text/javascript">
	
	function removeFriend(id, uiUpdateFunction){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'friend:remove-friend' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Successfully removed that friend."){
					// UI gets updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
	

</script>

friend/templates/friend/snippets/send_friend_request.html
<script type="text/javascript">
	
	function sendFriendRequest(id, uiUpdateFunction){
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'friend:friend-request' %}",
			timeout: 5000,
			data: payload,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "Friend request sent."){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
	

</script>